import uniqueId from 'lodash/uniqueId';

import {
  // IconUserCircle,
  IconUsers,
  IconDeviceAnalytics,
  IconTrendingUp,
  // IconLayoutadmin,
  // IconSettings2,
  // IconDatabase,
  // IconShieldLock,
  // IconChartBar,
  IconClipboardText,
  IconNotes,
  // IconCloudDataConnection,
  IconListDetails,
  // IconUserCog,
  // IconLock,
  IconHelpCircle,
  IconMessage,
  IconCirclePlus,
  IconApiApp,
  // IconLayersLinked,
  IconGraph,
  IconChartDots2,
  // IconTree,
  IconUserCog,
  IconBuildingStore,
  IconCurrencyDollar,
  IconDashboard
} from '@tabler/icons-react';

const Menuitems = [
  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconDashboard,
    href: '/admin/dashboard',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Users',
    icon: IconCirclePlus,
    href: '/admin/user-profile',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Franchise',
    icon: IconBuildingStore,
    href: '/admin/franchise',
    chipColor: 'secondary',
  },
  // {
  //   id: uniqueId(),
  //   title: 'User',
  //   icon: IconUsers,
  //   href: '/admin/user-dashboard',
  //   chipColor: 'secondary',
  // },
 {
    id: uniqueId(),
    title: 'Strategy ',
    icon: IconDeviceAnalytics,
    href: '/admin/strategy-dashboard',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Trade',
    icon: IconTrendingUp,
    href: '/admin/trade',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: ' Strategy MarketPlace ',
    icon: IconCirclePlus,
    href: '/admin/marketplace',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Plan Management',
    icon: IconCurrencyDollar,
    href: '/admin/plan-management',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Charges',
    icon: IconCurrencyDollar,
    href: '/admin/charges',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Usage',
    icon: IconHelpCircle,
    href: '/admin/usage',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Profile',
    icon: IconMessage,
    href: '/admin/profile',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Settings',
    icon: IconMessage,
    href: '/admin/settings',
    chipColor: 'secondary',
  },  {
    id: uniqueId(),
    title: 'Contact Support',
    icon: IconMessage,
    href: '/admin/contact-support',
    chipColor: 'secondary',
  },
  // {
  //   id: uniqueId(),
  //   title: 'Add User',
  //   icon: IconCirclePlus,
  //   href: '/admin/user-profile',
  //   chipColor: 'secondary',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'API',
  //   icon: IconChartDots2,
  //   href: '/admin/api',
  //   chipColor: 'secondary',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Platform',
  //   icon: IconTree,
  //   href: '/admin/platform-support',
  //   chipColor: 'secondary',
  // },
];

export default Menuitems;
